# CMake generated Testfile for 
# Source directory: /home/pi/sdk-folder/sdk-source/avs-device-sdk/ADSL/test
# Build directory: /home/pi/sdk-folder/sdk-build/ADSL/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(DirectiveProcessorTest.testNullptrDirective "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveProcessorTest" "--gtest_filter=DirectiveProcessorTest.testNullptrDirective")
add_test(DirectiveProcessorTest.testWrongDialogRequestId "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveProcessorTest" "--gtest_filter=DirectiveProcessorTest.testWrongDialogRequestId")
add_test(DirectiveProcessorTest.testSendNonBlocking "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveProcessorTest" "--gtest_filter=DirectiveProcessorTest.testSendNonBlocking")
add_test(DirectiveProcessorTest.testSendBlockingThenNonBlocking "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveProcessorTest" "--gtest_filter=DirectiveProcessorTest.testSendBlockingThenNonBlocking")
add_test(DirectiveProcessorTest.testOnUnregisteredDirective "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveProcessorTest" "--gtest_filter=DirectiveProcessorTest.testOnUnregisteredDirective")
add_test(DirectiveProcessorTest.testSetDialogRequestIdCancelsOutstandingDirectives "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveProcessorTest" "--gtest_filter=DirectiveProcessorTest.testSetDialogRequestIdCancelsOutstandingDirectives")
add_test(DirectiveRouterTest.testUnroutedDirective "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveRouterTest" "--gtest_filter=DirectiveRouterTest.testUnroutedDirective")
add_test(DirectiveRouterTest.testSettingADirectiveHandler "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveRouterTest" "--gtest_filter=DirectiveRouterTest.testSettingADirectiveHandler")
add_test(DirectiveRouterTest.testRegisteringMultipeHandler "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveRouterTest" "--gtest_filter=DirectiveRouterTest.testRegisteringMultipeHandler")
add_test(DirectiveRouterTest.testRemovingChangingAndNotChangingHandlers "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveRouterTest" "--gtest_filter=DirectiveRouterTest.testRemovingChangingAndNotChangingHandlers")
add_test(DirectiveRouterTest.testResultOfHandleDirectiveFailure "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveRouterTest" "--gtest_filter=DirectiveRouterTest.testResultOfHandleDirectiveFailure")
add_test(DirectiveRouterTest.testHandlerMethodsCanRunConcurrently "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveRouterTest" "--gtest_filter=DirectiveRouterTest.testHandlerMethodsCanRunConcurrently")
add_test(DirectiveSequencerTest.testNullptrExceptionSender "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveSequencerTest" "--gtest_filter=DirectiveSequencerTest.testNullptrExceptionSender")
add_test(DirectiveSequencerTest.testCreateAndDoneTrigger "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveSequencerTest" "--gtest_filter=DirectiveSequencerTest.testCreateAndDoneTrigger")
add_test(DirectiveSequencerTest.testNullptrDirective "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveSequencerTest" "--gtest_filter=DirectiveSequencerTest.testNullptrDirective")
add_test(DirectiveSequencerTest.testUnhandledDirective "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveSequencerTest" "--gtest_filter=DirectiveSequencerTest.testUnhandledDirective")
add_test(DirectiveSequencerTest.testEmptyDialogRequestId "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveSequencerTest" "--gtest_filter=DirectiveSequencerTest.testEmptyDialogRequestId")
add_test(DirectiveSequencerTest.testRemovingAndChangingHandlers "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveSequencerTest" "--gtest_filter=DirectiveSequencerTest.testRemovingAndChangingHandlers")
add_test(DirectiveSequencerTest.testBlockingDirective "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveSequencerTest" "--gtest_filter=DirectiveSequencerTest.testBlockingDirective")
add_test(DirectiveSequencerTest.testBlockingThenNonDialogDirective "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveSequencerTest" "--gtest_filter=DirectiveSequencerTest.testBlockingThenNonDialogDirective")
add_test(DirectiveSequencerTest.testBargeIn "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveSequencerTest" "--gtest_filter=DirectiveSequencerTest.testBargeIn")
add_test(DirectiveSequencerTest.testBlockingThenNonBockingOnSameDialogId "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveSequencerTest" "--gtest_filter=DirectiveSequencerTest.testBlockingThenNonBockingOnSameDialogId")
add_test(DirectiveSequencerTest.testThatBargeInDropsSubsequentDirectives "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveSequencerTest" "--gtest_filter=DirectiveSequencerTest.testThatBargeInDropsSubsequentDirectives")
add_test(DirectiveSequencerTest.testPreHandleDirectiveError "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveSequencerTest" "--gtest_filter=DirectiveSequencerTest.testPreHandleDirectiveError")
add_test(DirectiveSequencerTest.testHandleDirectiveError "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveSequencerTest" "--gtest_filter=DirectiveSequencerTest.testHandleDirectiveError")
add_test(DirectiveSequencerTest.testAddDirectiveHandlersWhileHandlingDirectives "/home/pi/sdk-folder/sdk-build/ADSL/test/DirectiveSequencerTest" "--gtest_filter=DirectiveSequencerTest.testAddDirectiveHandlersWhileHandlingDirectives")
add_test(MessageIntepreterTest.messageIsInValidJSON "/home/pi/sdk-folder/sdk-build/ADSL/test/MessageInterpreterTest" "--gtest_filter=MessageIntepreterTest.messageIsInValidJSON")
add_test(MessageIntepreterTest.messageHasInvalidDirectiveKey "/home/pi/sdk-folder/sdk-build/ADSL/test/MessageInterpreterTest" "--gtest_filter=MessageIntepreterTest.messageHasInvalidDirectiveKey")
add_test(MessageIntepreterTest.messageHasInvalidHeaderKey "/home/pi/sdk-folder/sdk-build/ADSL/test/MessageInterpreterTest" "--gtest_filter=MessageIntepreterTest.messageHasInvalidHeaderKey")
add_test(MessageIntepreterTest.messageHasInvalidNamespaceKey "/home/pi/sdk-folder/sdk-build/ADSL/test/MessageInterpreterTest" "--gtest_filter=MessageIntepreterTest.messageHasInvalidNamespaceKey")
add_test(MessageIntepreterTest.messageHasInvalidNameKey "/home/pi/sdk-folder/sdk-build/ADSL/test/MessageInterpreterTest" "--gtest_filter=MessageIntepreterTest.messageHasInvalidNameKey")
add_test(MessageIntepreterTest.messageHasInvalidMessageIdKey "/home/pi/sdk-folder/sdk-build/ADSL/test/MessageInterpreterTest" "--gtest_filter=MessageIntepreterTest.messageHasInvalidMessageIdKey")
add_test(MessageIntepreterTest.messageHasNoDialogRequestIdKey "/home/pi/sdk-folder/sdk-build/ADSL/test/MessageInterpreterTest" "--gtest_filter=MessageIntepreterTest.messageHasNoDialogRequestIdKey")
add_test(MessageIntepreterTest.messageHasNoPayloadKey "/home/pi/sdk-folder/sdk-build/ADSL/test/MessageInterpreterTest" "--gtest_filter=MessageIntepreterTest.messageHasNoPayloadKey")
add_test(MessageIntepreterTest.messageHasInvalidPayloadKey "/home/pi/sdk-folder/sdk-build/ADSL/test/MessageInterpreterTest" "--gtest_filter=MessageIntepreterTest.messageHasInvalidPayloadKey")
add_test(MessageIntepreterTest.messageIsValidDirective "/home/pi/sdk-folder/sdk-build/ADSL/test/MessageInterpreterTest" "--gtest_filter=MessageIntepreterTest.messageIsValidDirective")
subdirs("common")
